/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 LivingRoom.gltf --transform 
Files: LivingRoom.gltf [40.18KB] > C:\TanPhuc\Nam3\HK3\UI Design\Portfolio\public\LivingRoom-transformed.glb [3.41MB] (-8393%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function LivingRoom(props) {
  const { nodes, materials } = useGLTF('/LivingRoom-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Room.geometry} material={materials.Building} position={[0, 0.411, 0]} />
      <mesh geometry={nodes.Sofa.geometry} material={materials.Sofa} position={[-0.023, 0.611, 2.575]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Television.geometry} material={materials.TV} position={[-0.28, 3.631, -3.878]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Tv_Cabinet.geometry} material={materials.Cabinet} position={[0.028, 0.411, -3.357]} />
      <mesh geometry={nodes.Television001.geometry} material={materials.TVBacklight} position={[-0.28, 3.631, -3.878]} rotation={[Math.PI / 2, 0, 0]} scale={[1.967, 1.124, 1.124]} />
      <mesh geometry={nodes.water.geometry} material={materials.Mug} position={[-0.721, 0.869, -0.398]} scale={[1, 1.307, 1]} />
      <mesh geometry={nodes.Plane022.geometry} material={materials.Soundbar} position={[1.996, 1.782, -3.776]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Wall_Frame.geometry} material={materials['Wall Frame']} position={[-4, 3.335, -0.763]} rotation={[1.571, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Dvd} position={[-0.063, 0.642, -3.27]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Remote} position={[-1.038, 0.523, -0.463]} rotation={[0, 0.302, 0]} scale={[0.793, 1, 1]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Switch} position={[-0.101, 1.397, -0.498]} rotation={[0, 0.208, 0]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Led} position={[-0.542, 1.502, -3.376]} rotation={[Math.PI / 2, 0, 0]} scale={0.161} />
      <mesh geometry={nodes['1'].geometry} material={materials.Plant} position={[3.367, 1.125, -3.448]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['1001'].geometry} material={materials.Guitar} position={[-3.273, 1.667, -3.134]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Lamp} position={[-3.991, 4.441, 2.095]} rotation={[0, 0, -Math.PI / 2]} scale={1.091} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Pokeball} position={[-0.703, 0.569, -0.409]} rotation={[0, 0.078, 0]} scale={0.287} />
      <mesh geometry={nodes.Text.geometry} material={materials.Clock} position={[-2.054, 1.316, -3.16]} rotation={[0.787, 0.26, -0.253]} />
      <mesh geometry={nodes.Book4009.geometry} material={materials.Book} position={[-2.067, 0.604, -2.987]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Phone} position={[0.612, 1.388, -0.402]} rotation={[0, -0.163, 0]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Table} position={[0.024, 0.898, -0.836]} />
    </group>
  )
}

useGLTF.preload('/LivingRoom-transformed.glb')
