/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf --transform 
Files: scene.gltf [64.31KB] > C:\TanPhuc\Nam3\HK3\UI Design\Portfolio\public\scene-transformed.glb [1.55MB] (-2313%)
Author: amurin (https://sketchfab.com/amurin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-isometric-room-56cf7d5811304608b5e6d724195c6ccd
Title: Low Poly Isometric Room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.pared} position={[0.095, -0.373, 0.14]} scale={4.819} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.suelo} position={[0.095, -0.373, 0.14]} scale={4.819} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial001} position={[0.095, -0.373, 0.14]} scale={4.819} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.base_cama} position={[-1.049, -0.692, 1.149]} scale={1.419} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.pcinsidenormal} position={[-3.958, 1.431, -3.489]} scale={0.077} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.screen} position={[-3.781, 2.47, -1.132]} scale={1.456} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.PaletteMaterial002} position={[-2.793, 1.422, -2.237]} scale={[0.137, 0.04, 0.083]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.PaletteMaterial003} position={[-2.859, 1.4, -1.158]} scale={[0.266, 0.019, 0.797]} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.libro} position={[-2.771, 4.559, -3.744]} rotation={[Math.PI, 0, 2.849]} scale={[0.085, 0.433, 0.303]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
