/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/ArcadeRoom_V1.gltf --transform 
Files: public/ArcadeRoom_V1.gltf [89.17KB] > /Users/vochanhtin139/Desktop/ui-test/ArcadeRoom_V1-transformed.glb [63.91KB] (28%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ArcadeRoom_V1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Room.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.pipestop.geometry} material={materials.PaletteMaterial002} position={[0, -1.433, 0]} />
      <group position={[-2.322, 0, 3.237]} scale={0.844}>
        <mesh geometry={nodes.Plane003.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials['Material.005']} />
      </group>
      <mesh geometry={nodes.Monitor.geometry} material={materials.PaletteMaterial005} position={[-2.348, 1.663, 0.003]} rotation={[0, 0.412, 0]} scale={[0.442, 0.565, 0.442]} />
      <mesh geometry={nodes['80s-Retro-Sci-Fi-FPoster-and-lyer-Templates-for-Adobe-Photoshop'].geometry} material={materials.PaletteMaterial006} position={[0.675, 3.405, -3.999]} rotation={[Math.PI / 2, 0, 0]} scale={2.307} />
      <mesh geometry={nodes.Plane004.geometry} material={materials.PaletteMaterial003} position={[-1.581, 2.193, 2.97]} rotation={[0, 0, -0.156]} scale={0.048} />
      <mesh geometry={nodes.Plane010.geometry} material={materials.TVscreen} position={[0.007, 1.767, -2.849]} rotation={[0, Math.PI / 6, 0]} scale={0.875} />
      <instancedMesh args={[nodes.Plane031.geometry, materials.PaletteMaterial001, 10]} instanceMatrix={nodes.Plane031.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/ArcadeRoom_V1-transformed.glb')
